### ISSUE TITLE
SEGFAULT in __GI__IO_default_xsputn on Arch Linux

### ISSUE THREAD

**Issue by ignisf** [tgraf/bmon#66]
The segfault takes place intermittently when the network has high load. I suspect it has something to do with the number of codel classes.

```
#0  0x00007f095ebfa7a3 in __GI__IO_default_xsputn () from /usr/lib/libc.so.6
#1  0x00007f095ebcbfdc in vfprintf () from /usr/lib/libc.so.6
#2  0x00007f095ebcede6 in buffered_vfprintf () from /usr/lib/libc.so.6
#3  0x00007f095ebcc1ce in vfprintf () from /usr/lib/libc.so.6
#4  0x00007f095ec840c6 in __fprintf_chk () from /usr/lib/libc.so.6
#5  0x00005625c5d1a2e7 in fprintf (__fmt=0x5625c5d24110 "[DBG] %20s:%-4u %s: Creating element %d \"%s\"\n", __stream=<optimized out>) at /usr/include/bits/stdio2.h:97
#6  element_lookup (group=0x5625c6e9f640, name=name@entry=0x7ffe91604e00 "qdisc none (fq_codel)", id=id@entry=0, parent=0x5625d25739c0, flags=flags@entry=1) at element.c:155
#7  0x00005625c5d1cd2a in handle_tc_obj (tc=tc@entry=0x5625c6f6e5e0, prefix=prefix@entry=0x5625c5d25237 "qdisc", rdata=0x7ffe91604f50) at in_netlink.c:564
#8  0x00005625c5d1d024 in handle_qdisc (obj=0x5625c6f6e5e0, arg=<optimized out>) at in_netlink.c:670
#9  0x00007f095f70c0c8 in nl_cache_foreach_filter () from /usr/lib/libnl-3.so.200
#10 0x00005625c5d1d19d in find_qdiscs (rdata=0x7ffe91604f50, parent=3, ifindex=2) at in_netlink.c:627
#11 handle_class (obj=<optimized out>, arg=<optimized out>) at in_netlink.c:614
#12 0x00007f095f70c0c8 in nl_cache_foreach_filter () from /usr/lib/libnl-3.so.200
#13 0x00005625c5d1cba8 in find_classes (parent=0, rdata=0x7ffe91605020) at in_netlink.c:654
#14 0x00005625c5d1d073 in handle_qdisc (obj=0x5625c6f6e5e0, arg=<optimized out>) at in_netlink.c:682
#15 0x00007f095f70c0c8 in nl_cache_foreach_filter () from /usr/lib/libnl-3.so.200
#16 0x00005625c5d1d19d in find_qdiscs (rdata=0x7ffe916050c0, parent=3, ifindex=2) at in_netlink.c:627
#17 handle_class (obj=<optimized out>, arg=<optimized out>) at in_netlink.c:614
#18 0x00007f095f70c0c8 in nl_cache_foreach_filter () from /usr/lib/libnl-3.so.200
#19 0x00005625c5d1cba8 in find_classes (parent=0, rdata=0x7ffe91605190) at in_netlink.c:654
#20 0x00005625c5d1d073 in handle_qdisc (obj=0x5625c6f6e5e0, arg=<optimized out>) at in_netlink.c:682
#21 0x00007f095f70c0c8 in nl_cache_foreach_filter () from /usr/lib/libnl-3.so.200
#22 0x00005625c5d1d19d in find_qdiscs (rdata=0x7ffe91605230, parent=3, ifindex=2) at in_netlink.c:627
#23 handle_class (obj=<optimized out>, arg=<optimized out>) at in_netlink.c:614
#24 0x00007f095f70c0c8 in nl_cache_foreach_filter () from /usr/lib/libnl-3.so.200
#25 0x00005625c5d1cba8 in find_classes (parent=0, rdata=0x7ffe91605300) at in_netlink.c:654
#26 0x00005625c5d1d073 in handle_qdisc (obj=0x5625c6f6e5e0, arg=<optimized out>) at in_netlink.c:682
#27 0x00007f095f70c0c8 in nl_cache_foreach_filter () from /usr/lib/libnl-3.so.200
#28 0x00005625c5d1d19d in find_qdiscs (rdata=0x7ffe916053a0, parent=3, ifindex=2) at in_netlink.c:627
#29 handle_class (obj=<optimized out>, arg=<optimized out>) at in_netlink.c:614
#30 0x00007f095f70c0c8 in nl_cache_foreach_filter () from /usr/lib/libnl-3.so.200
---- snip ----
```

Core dump can be downloaded from here: http://petko.me/bmon/bmon.core.xz

**Comment by jimenezrick** [comment]
In case this is valuable, I'm also running Arch Linux with constant segfaults of bmon:
```
                                                     Stack trace of thread 16970:
                                                     #0  0x00007f47ec387ecd vfprintf (libc.so.6)
                                                     #1  0x00007f47ec43fd4b __vsnprintf_chk (libc.so.6)
                                                     #2  0x00007f47ec43fc75 __snprintf_chk (libc.so.6)
                                                     #3  0x00007f47ecc69f11 rtnl_tc_handle2str (libnl-route-3.so.200)
                                                     #4  0x000055a66dea1ece n/a (bmon)
                                                     #5  0x000055a66dea2326 n/a (bmon)
                                                     #6  0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #7  0x000055a66dea1d8b n/a (bmon)
                                                     #8  0x000055a66dea2297 n/a (bmon)
                                                     #9  0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #10 0x000055a66dea23d9 n/a (bmon)
                                                     #11 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #12 0x000055a66dea1d8b n/a (bmon)
                                                     #13 0x000055a66dea2297 n/a (bmon)
                                                     #14 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #15 0x000055a66dea23d9 n/a (bmon)
                                                     #16 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #17 0x000055a66dea1d8b n/a (bmon)
                                                     #18 0x000055a66dea2297 n/a (bmon)
                                                     #19 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #20 0x000055a66dea23d9 n/a (bmon)
                                                     #21 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #22 0x000055a66dea1d8b n/a (bmon)
                                                     #23 0x000055a66dea2297 n/a (bmon)
                                                     #24 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #25 0x000055a66dea23d9 n/a (bmon)
                                                     #26 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #27 0x000055a66dea1d8b n/a (bmon)
                                                     #28 0x000055a66dea2297 n/a (bmon)
                                                     #29 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #30 0x000055a66dea23d9 n/a (bmon)
                                                     #31 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #32 0x000055a66dea1d8b n/a (bmon)
                                                     #33 0x000055a66dea2297 n/a (bmon)
                                                     #34 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #35 0x000055a66dea23d9 n/a (bmon)
                                                     #36 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #37 0x000055a66dea1d8b n/a (bmon)
                                                     #38 0x000055a66dea2297 n/a (bmon)
                                                     #39 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #40 0x000055a66dea23d9 n/a (bmon)
                                                     #41 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #42 0x000055a66dea1d8b n/a (bmon)
                                                     #43 0x000055a66dea2297 n/a (bmon)
                                                     #44 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #45 0x000055a66dea23d9 n/a (bmon)
                                                     #46 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #47 0x000055a66dea1d8b n/a (bmon)
                                                     #48 0x000055a66dea2297 n/a (bmon)
                                                     #49 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #50 0x000055a66dea23d9 n/a (bmon)
                                                     #51 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #52 0x000055a66dea1d8b n/a (bmon)
                                                     #53 0x000055a66dea2297 n/a (bmon)
                                                     #54 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #55 0x000055a66dea23d9 n/a (bmon)
                                                     #56 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #57 0x000055a66dea1d8b n/a (bmon)
                                                     #58 0x000055a66dea2297 n/a (bmon)
                                                     #59 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #60 0x000055a66dea23d9 n/a (bmon)
                                                     #61 0x00007f47ececf5a9 nl_cache_foreach_filter (libnl-3.so.200)
                                                     #62 0x000055a66dea1d8b n/a (bmon)
                                                     #63 0x000055a66dea2297 n/a (bmon)
```

**Comment by JimBobKennedy** [comment]
This happens to me a lot lately. Is anyone working on it? Is this the wrong bug repository to get it some attention? I do not know the latest ways of open-source bug tracking.
