### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by carpikes** [tgraf/bmon#69]
Sometimes I got segfault at startup (Arch Linux x64), with gdb I can see this:
```
[...]
#87243 0x000055555557508b in find_qdiscs (rdata=0x7fffffffcf40, parent=3, ifindex=<optimized out>)
    at in_netlink.c:627
#87244 handle_class (obj=<optimized out>, arg=<optimized out>) at in_netlink.c:614
#87245 0x00007ffff65955a9 in nl_cache_foreach_filter () from /usr/lib/libnl-3.so.200
#87246 0x0000555555574238 in find_classes (parent=0, rdata=0x7fffffffd070) at in_netlink.c:654
#87247 0x00005555555743ec in handle_qdisc (obj=0x611000001940, arg=<optimized out>) at in_netlink.c:682
#87248 0x00007ffff65955a9 in nl_cache_foreach_filter () from /usr/lib/libnl-3.so.200
#87249 0x000055555557508b in find_qdiscs (rdata=0x7fffffffd180, parent=3, ifindex=<optimized out>)
    at in_netlink.c:627
#87250 handle_class (obj=<optimized out>, arg=<optimized out>) at in_netlink.c:614
#87251 0x00007ffff65955a9 in nl_cache_foreach_filter () from /usr/lib/libnl-3.so.200
---Type <return> to continue, or q <return> to quit---
#87252 0x0000555555574238 in find_classes (parent=0, rdata=0x7fffffffd2b0) at in_netlink.c:654
#87253 0x00005555555743ec in handle_qdisc (obj=0x611000001940, arg=<optimized out>) at in_netlink.c:682
#87254 0x00007ffff65955a9 in nl_cache_foreach_filter () from /usr/lib/libnl-3.so.200
#87255 0x000055555557508b in find_qdiscs (rdata=0x7fffffffd3c0, parent=3, ifindex=<optimized out>)
    at in_netlink.c:627
#87256 handle_class (obj=<optimized out>, arg=<optimized out>) at in_netlink.c:614
#87257 0x00007ffff65955a9 in nl_cache_foreach_filter () from /usr/lib/libnl-3.so.200
#87258 0x0000555555574238 in find_classes (parent=0, rdata=0x7fffffffd4f0) at in_netlink.c:654
#87259 0x00005555555743ec in handle_qdisc (obj=0x611000001bc0, arg=<optimized out>) at in_netlink.c:682
#87260 0x00007ffff65955a9 in nl_cache_foreach_filter () from /usr/lib/libnl-3.so.200
#87261 0x000055555557508b in find_qdiscs (rdata=0x7fffffffd600, parent=1, ifindex=<optimized out>)
    at in_netlink.c:627
#87262 handle_class (obj=<optimized out>, arg=<optimized out>) at in_netlink.c:614
#87263 0x00007ffff65955a9 in nl_cache_foreach_filter () from /usr/lib/libnl-3.so.200
#87264 0x0000555555574238 in find_classes (parent=4294967295, rdata=0x7fffffffd730) at in_netlink.c:654
#87265 0x0000555555574440 in handle_qdisc (obj=obj@entry=0x6110000016c0, arg=arg@entry=0x7fffffffd830)
    at in_netlink.c:679
#87266 0x0000555555574cd2 in handle_tc (link=<optimized out>, e=0x617000000b00) at in_netlink.c:702
#87267 do_link (obj=<optimized out>, arg=<optimized out>) at in_netlink.c:824
#87268 0x00007ffff65955a9 in nl_cache_foreach_filter () from /usr/lib/libnl-3.so.200
#87269 0x0000555555572e7f in module_foreach_run_enabled (ss=0x555555793fc0 <input_subsys>)
    at module.c:55
#87270 0x00005555555681ff in main (argc=<optimized out>, argv=<optimized out>) at bmon.c:349
```

**Comment by slashdd** [comment]
@carpikes do you still get segfault ? Do you have a reproducer you can share ?
